
name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Installing dependencies
      run: npm install
    - name: Eslint
      run: npm run lint
    - name: Typescript
      run: npm run type-check
