
name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Installing dependencies
    - run: npm install
    - name: Running lint test
      run: |
        ./node_modules/.bin/eslint --init
        npm run lint
    - name: Running type check
      run: npm run type-check
