
name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Installing dependencies
      run: npm install
    - name: Build server and client
      run: npm run build
    - name: Lint
      run: npm run lint
